### ISSUE TITLE
'Add comment' button has black font, while it should be white.

### ISSUE THREAD

**Issue by gsancheznearsoft** [Nearsoft/questions#93] opened 2016-06-01 18:42 UTC
To match the website's style, the font from said button should be white instead of black.

Screenshot of current behavior:
![image](https://cloud.githubusercontent.com/assets/2767847/15721458/b888291e-27fe-11e6-8e01-b8cb652b5995.png)

**Comment by wdonet** [comment] 2016-06-20 13:17
Closing since it's not reproducible

**Closed by wdonet** 2016-06-20 13:17 UTC
Labels: _bug
